# Generated by Django 6.0.4 on 2026-04-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='midtrans_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='snap_token',
        ),
    ]
